28th October'23 Live Class:Notebook implementation of end to end project

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("D:/Diamond price prediction project/notebooks/data/train.csv")

In [3]:
data.drop(labels=["id"],axis=1,inplace=True)

In [4]:
data

        carat        cut color clarity  depth  table     x     y     z  price
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
...       ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67   1130
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47   2874
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62   3036
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81    681
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48   2258

[193573 rows x 10 columns]

In [5]:
x = dX=data.drop(labels=["price"],axis=1)

In [6]:
y=data[["price"]]

In [7]:
x

        carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [8]:
y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [9]:
catagorical_col = x.select_dtypes(include='object').columns

In [10]:
catagorical_col

Index(['cut', 'color', 'clarity'], dtype='object')

In [11]:
numerical_col = x.select_dtypes(exclude='object').columns

In [12]:
numerical_col

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [13]:
x.select_dtypes(include='object')

              cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [14]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [15]:
from sklearn.impute import SimpleImputer  ## handling missing values 
from sklearn.preprocessing import StandardScaler ## handling feature scaling 
from sklearn.preprocessing import OrdinalEncoder  # ordinal encoding 
## pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:

num_pipeline=Pipeline(
    
    
    steps=[
        
        ('imputer',SimpleImputer()),
        ('scaler', StandardScaler())
    ]
    
    
)

In [17]:
cat_pipeline=Pipeline(
    
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories]))
    ]
    
)

In [18]:
preprocessor = ColumnTransformer(
    [
        ('num_pipeline',num_pipeline,numerical_col),
        ('cat_pipeline',cat_pipeline,catagorical_col)     
    ]
)

In [19]:
## Train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=30)

In [20]:
x_train

        carat      cut color clarity  depth  table     x     y     z
168192   0.34    Ideal     I    VVS2   60.9   57.0  4.56  4.53  2.76
35202    0.90     Good     E     SI1   63.8   57.0  6.07  6.03  3.87
41091    1.02  Premium     G     VS1   62.7   58.0  6.35  6.39  4.00
31239    0.32  Premium     G     VS2   62.1   59.0  4.37  4.35  2.71
45722    0.35    Ideal     J    VVS2   61.1   56.0  4.53  4.57  2.78
...       ...      ...   ...     ...    ...    ...   ...   ...   ...
66455    0.31    Ideal     E     SI1   61.8   56.0  4.31  4.35  2.68
46220    1.25    Ideal     G     SI2   62.0   56.0  6.88  6.95  4.28
98804    1.00     Good     G     SI1   63.5   56.0  6.29  6.37  4.02
48045    1.10    Ideal     G     VS1   59.9   60.0  6.68  6.77  4.01
169765   0.91    Ideal     G     SI1   62.7   57.0  6.14  6.18  3.86

[135501 rows x 9 columns]

In [21]:
preprocessor.fit_transform(x_train)

array([[-0.97543926, -0.84960654, -0.12153081, ...,  4.        ,
         5.        ,  5.        ],
       [ 0.2351953 ,  1.83363716, -0.12153081, ...,  1.        ,
         1.        ,  2.        ],
       [ 0.49461699,  0.81585507,  0.39980029, ...,  3.        ,
         3.        ,  4.        ],
       ...,
       [ 0.45138004,  1.55606023, -0.6428619 , ...,  1.        ,
         3.        ,  2.        ],
       [ 0.66756478, -1.77486298,  1.44246248, ...,  4.        ,
         3.        ,  4.        ],
       [ 0.25681377,  0.81585507, -0.12153081, ...,  4.        ,
         3.        ,  2.        ]])

In [22]:
preprocessor.fit_transform(x_test)

array([[-0.56047339, -0.94666761, -0.63268646, ...,  3.        ,
         1.        ,  3.        ],
       [-0.17167285,  0.99091296, -0.11194742, ...,  2.        ,
         4.        ,  2.        ],
       [-1.05727407,  0.25278703, -0.11194742, ...,  4.        ,
         4.        ,  7.        ],
       ...,
       [-0.19327288, -3.34557688,  1.45026972, ...,  3.        ,
         6.        ,  3.        ],
       [-0.81967374, -0.20854168, -0.11194742, ...,  4.        ,
         3.        ,  2.        ],
       [ 2.61473099, -0.76213612,  1.45026972, ...,  3.        ,
         6.        ,  3.        ]])

In [23]:
preprocessor.get_feature_names_out()

array(['num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [24]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.fit_transform(x_test),columns=preprocessor.get_feature_names_out())

In [25]:
x_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.975439,-0.849607,-0.121531,-1.042757,-1.080970,-1.123150,4.0,5.0,5.0
1,0.235195,1.833637,-0.121531,0.318447,0.279859,0.485354,1.0,1.0,2.0
2,0.494617,0.815855,0.399800,0.570855,0.606458,0.673737,3.0,3.0,4.0
3,-1.018676,0.260701,0.921131,-1.214034,-1.244270,-1.195605,3.0,3.0,3.0
4,-0.953821,-0.664555,-0.642862,-1.069801,-1.044681,-1.094168,4.0,6.0,5.0
...,...,...,...,...,...,...,...,...,...
135496,-1.040295,-0.016876,-0.642862,-1.268122,-1.244270,-1.239078,4.0,1.0,2.0
135497,0.991842,0.168176,-0.642862,1.048629,1.114501,1.079486,4.0,3.0,1.0
135498,0.451380,1.556060,-0.642862,0.516768,0.588314,0.702719,1.0,3.0,2.0
135499,0.667565,-1.774863,1.442462,0.868337,0.951202,0.688228,4.0,3.0,4.0
135500,0.256814,0.815855,-0.121531,0.381549,0.415942,0.470863,4.0,3.0,2.0

In [26]:
x_test

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.560473,-0.946668,-0.632686,-0.425330,-0.459668,-0.498885,3.0,1.0,3.0
1,-0.171673,0.990913,-0.111947,-0.037825,-0.024281,0.040318,2.0,4.0,2.0
2,-1.057274,0.252787,-0.111947,-1.299471,-1.294159,-1.271258,4.0,4.0,7.0
3,0.973129,-0.208542,1.971009,1.052598,1.000693,0.987567,3.0,3.0,3.0
4,-0.927674,-1.315731,0.408792,-1.002083,-0.985760,-1.067235,3.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...
58067,1.016329,1.175444,-0.632686,1.007539,1.046046,1.162444,2.0,4.0,3.0
58068,-0.992474,0.252787,-1.153426,-1.137259,-1.121819,-1.110954,4.0,2.0,6.0
58069,-0.193273,-3.345577,1.450270,0.106363,0.075496,-0.221997,3.0,6.0,3.0
58070,-0.819674,-0.208542,-0.111947,-0.848883,-0.876913,-0.877785,4.0,3.0,2.0
58071,2.614731,-0.762136,1.450270,2.143021,2.043808,2.022254,3.0,6.0,3.0

linear regression <br>
ridge regressin <br>
lasso regression <br>
elastic net<br>

In [27]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,median_absolute_error,mean_squared_error

In [28]:
import numpy as np
def evaluate_model(true,predicted):
    mae = median_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted))
    r2_square = r2_score(true,predicted)
    return mae,rmse,r2_square

In [29]:
 ## Train multiple models 
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [30]:

trained_model_list=[]
model_list=[]
r2_list=[]

In [31]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [32]:
for i in range(len(list(models))):
    print(i)

0
1
2
3

In [33]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [34]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [35]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()

In [36]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

    #make predictions
    y_pred=model.predict(x_test)

    mae,rmse,r2_square = evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE",rmse)
    print("MAE",mae)
    print("R2 score", r2_square*100)

    r2_list.append(r2_square)

    print('='*35) 
    print('\n')

LinearRegression
Model Training Performance
RMSE 1014.0328726603915
MAE 461.1130810040063
R2 score 93.68748691429599
===================================


Lasso
Model Training Performance
RMSE 1014.005414243781
MAE 463.9994577020859
R2 score 93.68782877553554
===================================


Ridge
Model Training Performance
RMSE 1014.0343503475384
MAE 461.195213077581
R2 score 93.68746851661581
===================================


Elasticnet
Model Training Performance
RMSE 1513.3315484365123
MAE 809.0665776955375
R2 score 85.94061269062263
===================================

In [37]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [38]:
r2_list

[0.9368748691429599, 0.9368782877553554, 0.936874685166158, 0.8594061269062263]